set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)

set(ROCKNIX_TOOLCHAIN "/home/ubuntu/distribution/build.ROCKNIX-RK3326.aarch64/toolchain")
set(CROSS_PREFIX "aarch64-rocknix-linux-gnueabi")
set(SYSROOT "${ROCKNIX_TOOLCHAIN}/${CROSS_PREFIX}/sysroot")

set(CMAKE_SYSROOT ${SYSROOT})
set(CMAKE_C_COMPILER "${ROCKNIX_TOOLCHAIN}/bin/${CROSS_PREFIX}-gcc")
set(CMAKE_CXX_COMPILER "${ROCKNIX_TOOLCHAIN}/bin/${CROSS_PREFIX}-g++")
set(CMAKE_AR "${ROCKNIX_TOOLCHAIN}/bin/${CROSS_PREFIX}-ar" CACHE FILEPATH "Archiver")
set(CMAKE_RANLIB "${ROCKNIX_TOOLCHAIN}/bin/${CROSS_PREFIX}-ranlib" CACHE FILEPATH "Ranlib")
set(CMAKE_STRIP "${ROCKNIX_TOOLCHAIN}/bin/${CROSS_PREFIX}-strip" CACHE FILEPATH "Strip")
set(CMAKE_LINKER "${ROCKNIX_TOOLCHAIN}/bin/${CROSS_PREFIX}-ld" CACHE FILEPATH "Linker")

set(CMAKE_FIND_ROOT_PATH ${SYSROOT})
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

set(ENV{PKG_CONFIG_PATH} "${SYSROOT}/usr/lib/pkgconfig")
set(ENV{PKG_CONFIG_SYSROOT_DIR} "${SYSROOT}")
